/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArmoryRouteImport } from './routes/armory'
import { Route as IntelRouteImport } from './routes/intel'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as PlayRouteImport } from './routes/play'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArmoryRoute = ArmoryRouteImport.update({
  id: '/armory',
  path: '/armory',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelRoute = IntelRouteImport.update({
  id: '/intel',
  path: '/intel',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/armory': typeof ArmoryRoute
  '/intel': typeof IntelRoute
  '/ops': typeof OpsRoute
  '/play': typeof PlayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/armory': typeof ArmoryRoute
  '/intel': typeof IntelRoute
  '/ops': typeof OpsRoute
  '/play': typeof PlayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/armory': typeof ArmoryRoute
  '/intel': typeof IntelRoute
  '/ops': typeof OpsRoute
  '/play': typeof PlayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/armory' | '/intel' | '/ops' | '/play'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/armory' | '/intel' | '/ops' | '/play'
  id: '__root__' | '/' | '/armory' | '/intel' | '/ops' | '/play'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArmoryRoute: typeof ArmoryRoute
  IntelRoute: typeof IntelRoute
  OpsRoute: typeof OpsRoute
  PlayRoute: typeof PlayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/armory': {
      id: '/armory'
      path: '/armory'
      fullPath: '/armory'
      preLoaderRoute: typeof ArmoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intel': {
      id: '/intel'
      path: '/intel'
      fullPath: '/intel'
      preLoaderRoute: typeof IntelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArmoryRoute: ArmoryRoute,
  IntelRoute: IntelRoute,
  OpsRoute: OpsRoute,
  PlayRoute: PlayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
